CREATE DATABASE PROYECTO;
GO

USE PROYECTO;
GO


CREATE TABLE PRODUCTO(
	ID_PRODUCTO VARCHAR(5) PRIMARY KEY,
	NOMBRE VARCHAR(30),
	LOCALIZACION VARCHAR(50),
	STOCK_MIN INT
)  

CREATE TABLE PRODUCTOS_AUX (
    ID_PRODUCTO VARCHAR(5) FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
    CANTIDAD INT
);

CREATE TABLE MATERIALES(
    ID_MATERIAL VARCHAR(5) PRIMARY KEY,
    ID_PRODUCTO VARCHAR(5) FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
    SUBCATEGORIA VARCHAR(20),
    DESCRIPCION TEXT,
    FECHA_COMPRA DATE,
    MIN_STOCK INT CHECK (MIN_STOCK >= 1)
);

CREATE TABLE REACTIVOS(
    ID_REACTIVO VARCHAR(5) PRIMARY KEY,
    ID_PRODUCTO VARCHAR(5) FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
    CANTIDAD INT,
    FECHA_CADUCIDAD DATE,
    GRADO_PUREZA VARCHAR(5) CHECK (RIGHT(GRADO_PUREZA, 1) = '%')
);

CREATE TABLE ALMACEN(
    ID_ALMACEN VARCHAR(5) PRIMARY KEY,
    NOMBRE VARCHAR(20)
);

CREATE TABLE UBICACION(
    ID_UBICACION VARCHAR(5) PRIMARY KEY,
	ID_ALMACEN VARCHAR(5) FOREIGN KEY REFERENCES ALMACEN(ID_ALMACEN),
    LOCALIZACION VARCHAR(20)
);

CREATE TABLE FORMATO(
    Cod_Formato VARCHAR(5) PRIMARY KEY,
    NOMBRE VARCHAR(20)
);

CREATE TABLE RIESGOS(
    ID_RIESGO INT PRIMARY KEY IDENTITY,
    IMAGEN_REISGO IMAGE
);

CREATE TABLE NUMERO_SERIE(
    ID_SERIE VARCHAR(5) PRIMARY KEY
);
