CREATE DATABASE PROYECTO;
GO

USE PROYECTO;
GO


CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT PRIMARY KEY,
	NOMBRE_PRODUCTO VARCHAR(70),
	LOCALIZACION VARCHAR(50),
	STOCK_MIN INT
)  

CREATE TABLE PRODUCTOS_AUX (
	ID_PRODUCTO_AUX INT PRIMARY KEY FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
	NOMBRE_PRODAUX VARCHAR(25),
	FORMATO_PRODAUX TEXT,
	CANTIDAD INT,
	LOCALIZACION_PRODAUX VARCHAR(50),
	UBICACION_PRODAUX VARCHAR(50),
	STOCK_MINIMO_PRODAUX INT,
);
DROP TABLE PRODUCTOS_AUX

CREATE TABLE MATERIAL(
    ID_MATERIAL INT PRIMARY KEY FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
	NOMBRE_MATERIAL VARCHAR(60),
	LOCALIZACION VARCHAR(25),
	UBICACION VARCHAR(40),
	SUBCATEGORIA VARCHAR(20),
	DESCRIPCION TEXT,
	CANTIDAD INT,
	STOCK_MINIMO_MATERIAL INT,
	FECHA_COMPRA DATE,
   
);



CREATE TABLE REACTIVOS(
    ID_REACTIVO INT PRIMARY KEY FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
    NOMBRE_REACTIVO VARCHAR(60),
	FORMATO_REACTIVO VARCHAR(10),
    CANTIDAD_REACTIVO INT,
	LOCALIZACION_REACTIVO VARCHAR(25) CHECK (LOCALIZACION_REACTIVO = 'Almacén principal'),
	UBICACION_REACTIVO VARCHAR(5),
	GRADO_PUREZA VARCHAR(30),
    FECHA_CADUCIDAD VARCHAR(10),
	STOCK_MINIMO_REACTIVOS INT
	
);
--ALTER TABLE REACTIVOS
--ADD ID_RIESGO INT;
--ALTER TABLE REACTIVOS
--ADD CONSTRAINT FK_REACTIVOS_ID_RIESGO
--FOREIGN KEY (ID_RIESGO) REFERENCES RIESGOS(ID_RIESGO);


CREATE TABLE ALMACEN(
    ID_ALMACEN VARCHAR(5) PRIMARY KEY,
    NOMBRE_ALMACEN VARCHAR(20)
);

CREATE TABLE UBICACION(
    ID_UBICACION VARCHAR(5) PRIMARY KEY,
	ID_ALMACEN VARCHAR(5) FOREIGN KEY REFERENCES ALMACEN(ID_ALMACEN),
	ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
    LOCALIZACION VARCHAR(20)
);


CREATE TABLE FORMATO(
    Cod_Formato VARCHAR(5) PRIMARY KEY,
	ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
    FORMATO VARCHAR(20)
);

CREATE TABLE RIESGOS(
    ID_RIESGO INT PRIMARY KEY,
    IMAGEN_RIESGO VARCHAR(max)
);
--ALTER TABLE RIESGOS
--DROP COLUMN IMAGEN_RIESGO;

--ALTER TABLE RIESGOS
--ADD IMAGEN_RIESGO VARCHAR(max);



CREATE TABLE REACTIVO_RIESGO(
	ID_RIESGO INT,
	ID_REACTIVO INT,
	PRIMARY KEY (ID_RIESGO, ID_REACTIVO),
	CONSTRAINT FK_RIESGO_REACTIVO 
		FOREIGN KEY (ID_RIESGO) REFERENCES RIESGOS(ID_RIESGO),
	CONSTRAINT FK_RIESGO_REACTIVO2 
		FOREIGN KEY (ID_REACTIVO) REFERENCES REACTIVOS(ID_REACTIVO)
);

CREATE TABLE NUMERO_SERIE(
    NUMERO_SERIE VARCHAR(10) PRIMARY KEY,
	ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO)
);

